//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio1_Aplicación_base.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Laboratorio1_AP_DataBaseEntities : DbContext
    {
        public Laboratorio1_AP_DataBaseEntities()
            : base("name=Laboratorio1_AP_DataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tablaTiempodB> tablaTiempodB { get; set; }
        public virtual DbSet<tablaUsuariosdB> tablaUsuariosdB { get; set; }
    }
}
