//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio1_Aplicación_base.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tablaUsuariosdB
    {
        public int ID { get; set; }
        public string nombre { get; set; }
        public string rol { get; set; }
        public string correo { get; set; }
        public string tipoDocumento { get; set; }
        public string numeroDocumento { get; set; }
        public string password { get; set; }
    }
}
